CMake: Make project compile-able with clang
The project was not compile-able when using `clang` as `CC` and
`clang++` as `CXX`. The problem is that the z3 library, that we use,
can be compiled with gcc library and clang when linking our project
with it then needs to explicitly know what libraries should be used
for linking (`stdc++`, `gcc_s`).

Errors encountered while compiling/linking with clang:
- `undefined reference to symbol '_ZNSt6localeD1Ev@@GLIBCXX_3.4'`,
- `undefined reference to symbol '_Unwind_Resume@@GCC_3.0'`.

The project (SimpLL library) is compile-able with `clang` after
adding `-lstdc++` and `lgcc_s` flags.