build-kernel: Add logging for debugging issues
Sometimes when running `diffkemp build-kernel` command to build
snapshots of a kernel, the `build-kernel` can be unable to compile the
source files of functions to LLVM IR. In these cases the output
contains the following:

```
<function-name>: source not found
```

This information is not enough to find the reason why the compilation
failed and manual debugging is necessary. For this reason, this commit
introduces logging for `diffkemp build-kernel` command to speed up the
debugging process by logging certain informations.

For logging is used python logging module [1].
The detail of logging is based on how DiffKemp is run:
- `diffkemp build-kernel`: Logs error messages (not used right
  now),
- `diffkemp -v build-kernel`: Logs warning messages (not used right
  now),
- `diffkemp -d build-kernel`: Logs information messages (not used right
  now),
- `diffkemp -dd build-kernel`: Logs debug messages (used in this
  commit).
The level of logging detail is created for a future use and to be
partly consistent with `diffkemp compare` command.

When running `diffkemp build-kernel` command for:
- `__bpf_get_stackid` function
- on repo [2]
- on commit `e17d62fedd10ae56e2426858bd0757da544dbc73`

the previous output was (and current without `-dd` option is):

```
__bpf_get_stackid: source not found
```

when the `-dd` option is provided, the following can be extracted from
the output (which helps to solve the problem).

```
In file included from ./include/linux/nodemask.h:94:
./include/linux/random.h:24:39: error: use of undeclared identifier 'latent_entropy'; did you mean 'add_latent_entropy'?
   24 |         add_device_randomness((const void *)&latent_entropy, sizeof(latent_entropy));
      |                                              ^~~~~~~~~~~~~~
      |                                              add_latent_entropy
./include/linux/random.h:21:20: note: 'add_latent_entropy' declared here
   21 | static inline void add_latent_entropy(void)
      |                    ^
./include/linux/random.h:24:62: error: use of undeclared identifier 'latent_entropy'; did you mean 'add_latent_entropy'?
   24 |         add_device_randomness((const void *)&latent_entropy, sizeof(latent_entropy));
      |                                                                     ^~~~~~~~~~~~~~
      |                                                                     add_latent_entropy
./include/linux/random.h:21:20: note: 'add_latent_entropy' declared here
   21 | static inline void add_latent_entropy(void)
      |                    ^
```

[1] https://docs.python.org/3/library/logging.html
[2] https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git