RPM: make python3-setuptools a runtime dependency
snapshot.py imports pkg_resources to include information about the used
DiffKemp version in the snapshot. We have seen some failures when using
DiffKemp RPM of kind:

    $ diffkemp build ...
    Traceback (most recent call last):
      File "/usr/bin/diffkemp", line 3, in <module>
        from diffkemp import diffkemp
      File "/usr/lib64/python3.11/site-packages/diffkemp/diffkemp.py", line 3, in <module>
        from diffkemp.config import Config
      File "/usr/lib64/python3.11/site-packages/diffkemp/config.py", line 3, in <module>
        from diffkemp.snapshot import Snapshot
      File "/usr/lib64/python3.11/site-packages/diffkemp/snapshot.py", line 14, in <module>
        import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'

Since pkg_resources is a part of setuptools, make python3-setuptools a
runtime dependency.